import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
export interface GodotPrompt { name: string; config: { title: string; description: string; argsSchema?: Record<string, z.ZodType> }; build: (args: Record<string, string>) => string }
export const GODOT_PROMPTS: GodotPrompt[] = [
  { name: "orient", config: { title: "Orient in the Godot project", description: "Read live editor and project-map state in one pass." }, build: () => "Call `godot_orient` and summarize only actionable project, scene, selection, import, play, git, and project-map state." },
  { name: "analyze_scene", config: { title: "Analyze the edited scene", description: "Inspect node structure, dependencies, ownership, and visuals." }, build: () => "Inspect the edited scene with `godot_get_scene_tree`, the current selection, relevant resource dependencies, and the matching 2D or 3D capture. Report prioritized structural, ownership, dependency, and visual issues without changing anything." },
  { name: "verify", config: { title: "Verify changes", description: "Run Godot import, syntax, and configured project tests." }, build: () => "Run `godot_verify`. If `res://tests/run_tests.gd` exists, also run `godot_test_run` and report its independent pass, fail, or timeout result. Never present import/syntax success as test execution." },
  { name: "new_script", config: { title: "Create verified GDScript", description: "Reflect APIs, write a script, import, and verify.", argsSchema: { name: z.string(), description: z.string() } }, build: (args) => `Create ${args.name || "a new GDScript"}: ${args.description || "(behavior)"}. Query relevant APIs with godot_reflect, create it under a suitable res:// path, refresh the filesystem, then run godot_verify and fix any failure.` },
  { name: "play", config: { title: "Run the project", description: "Run the correct scene and inspect editor play state." }, build: () => "Inspect open scenes, run the appropriate current or main scene with `godot_run_project`, confirm `godot_get_play_status`, and report what was actually launched. Stop it when the task requires cleanup." },
  { name: "debug", config: { title: "Debug a live run", description: "Collect runtime diagnostics, performance evidence, and a game screenshot in one bounded run." }, build: () => "Call `godot_debug_run` for the appropriate scene. Prioritize grouped errors and warnings, then performance findings and the captured game image. Treat `clean` as no issues observed in the bounded window, and call out any `unverified` evidence gap." },
];
export function registerPrompts(server: McpServer): void { for (const prompt of GODOT_PROMPTS) server.registerPrompt(prompt.name, prompt.config as never, ((args: Record<string, string> = {}) => ({ messages: [{ role: "user" as const, content: { type: "text" as const, text: prompt.build(args) } }] })) as never); }
