import path from "node:path";
import type { Brain } from "./brain.js";
import type { KnowledgeBase, KnowledgeEntity, KnowledgeManifest } from "./knowledge.js";

export function renderBrainMarkdown(brain: Brain, manifest?: KnowledgeManifest): string {
  const coverage = manifest?.coverage ?? brain.assets.coverage;
  const lines = [
    "# Godot Project Brain",
    "",
    `> Generated by **Godot Vibe OS** at ${new Date(brain.generatedAt).toISOString()}.`,
    "",
    "## Project",
    "",
    `- Name: ${brain.identity.projectName ?? "(unknown)"}`,
    `- Path: \`${brain.identity.projectPath}\``,
    `- Godot feature version: ${brain.engine.versionHint ?? "(not declared)"}`,
    `- Main scene: ${brain.engine.mainScene ? `\`${brain.engine.mainScene}\`` : "(not set)"}`,
    `- Renderer: ${brain.engine.renderer ?? "(project default)"}`,
    `- .NET: ${brain.engine.usesDotnet ? "enabled" : "not detected"}`,
    "",
    "## Indexed surface",
    "",
    `- Coverage: ${coverage.complete ? "complete" : coverage.truncated ? "truncated" : "incomplete"} (${coverage.scanned}/${coverage.discovered}, cap ${coverage.cap})`,
    `- Scenes: ${brain.assets.scenes.length}`,
    `- Resources: ${brain.assets.resources.length}`,
    `- GDScript files: ${brain.assets.gdScripts.length}`,
    `- C# files: ${brain.assets.csharpScripts.length}`,
    `- Shaders: ${brain.assets.shaders.length}`,
    `- Addons: ${brain.assets.addons.length}`,
    `- Scan/read errors: ${coverage.errors.length}`,
    "",
    "## Godot architecture signals",
    "",
    `- Global classes: ${brain.architecture.namedClasses.length}`,
    `- Autoloads: ${brain.engine.autoloads.map((entry) => entry.name).join(", ") || "none"}`,
    `- Signals: ${brain.architecture.signalCount}`,
    `- Exported properties: ${brain.architecture.exportCount}`,
    `- Tool scripts: ${brain.architecture.toolScripts.length}`,
    `- Input actions: ${brain.engine.inputActions.join(", ") || "none"}`,
    `- Networking API match: ${yesNo(brain.architecture.hasNetworking)}`,
    `- Save API match: ${yesNo(brain.architecture.hasSaveSystem)}`,
    `- Input API match: ${yesNo(brain.architecture.hasInputHandling)}`,
    "",
  ];
  appendPaths(lines, "Scenes", brain.assets.scenes, 40);
  appendPaths(lines, "Autoload scripts", brain.engine.autoloads.map((entry) => entry.path), 30);
  return lines.join("\n");
}

export function renderClaudeContextMarkdown(brain: Brain, manifest?: KnowledgeManifest): string {
  const coverage = manifest?.coverage ?? brain.assets.coverage;
  const projectName = brain.identity.projectName ?? path.basename(brain.identity.projectPath);
  return [
    `# AI Project Context: ${projectName}`,
    "",
    "Read `.godot-vibe/brain/manifest.json` first. Query the JSONL graph for focused questions instead of rescanning the project.",
    "",
    "## Verified static context",
    "",
    `- Godot ${brain.engine.versionHint ?? "version not declared"}; renderer ${brain.engine.renderer ?? "project default"}; main scene ${brain.engine.mainScene ?? "not set"}.`,
    `- ${brain.assets.scenes.length} scenes, ${brain.assets.resources.length} resources, ${brain.assets.gdScripts.length} GDScript files, ${brain.assets.csharpScripts.length} C# files, ${brain.assets.addonScripts.length} addon scripts.`,
    `- Coverage is ${coverage.complete ? "complete" : coverage.truncated ? "truncated" : "incomplete"}: ${coverage.scanned}/${coverage.discovered} indexed files, cap ${coverage.cap}, ${coverage.errors.length} errors.`,
    "",
    "## Working rules",
    "",
    "- Prefer Godot Vibe OS tools for scene-tree inspection and mutation; do not hand-edit `.tscn` or `.tres` serialization.",
    "- Run Godot's parser/import verification after GDScript or resource changes.",
    "- Treat the live editor as authoritative for runtime state, instantiated nodes, and imported resources.",
    "- Refresh the project brain after scripts, scenes, resources, autoloads, or input actions change.",
    "",
    "## Knowledge files",
    "",
    "- `.godot-vibe/brain/index.md` — compact map and coverage boundary",
    "- `.godot-vibe/brain/manifest.json` — freshness and fingerprints",
    "- `.godot-vibe/brain/entities.jsonl` — projects, addons, scenes, resources, scripts, classes, modules, and shaders",
    "- `.godot-vibe/brain/relations.jsonl` — contains, declares, extends, references, and instantiates edges",
    "- `.godot-vibe/conventions.md` — user-maintained project rules",
    "",
  ].join("\n");
}

export function renderKnowledgeIndexMarkdown(brain: KnowledgeBase): string {
  const { manifest, entities, relations } = brain;
  const kinds = groupByKind(entities);
  const relationCounts = new Map<string, number>();
  for (const relation of relations) relationCounts.set(relation.kind, (relationCounts.get(relation.kind) ?? 0) + 1);
  const lines = [
    `# Godot Knowledge Map: ${manifest.project.name}`,
    "",
    `> Schema v${manifest.schemaVersion}; generated ${new Date(manifest.generatedAt).toISOString()}.`,
    "",
    "## Coverage and freshness",
    "",
    `- State: ${manifest.dirty.value ? "dirty" : "clean"}`,
    `- Coverage: ${manifest.coverage.complete ? "complete" : manifest.coverage.truncated ? "truncated" : "incomplete"}`,
    `- Files: ${manifest.coverage.scanned}/${manifest.coverage.discovered}; cap ${manifest.coverage.cap}`,
    `- First-party: ${manifest.coverage.scopes.firstParty.scanned}/${manifest.coverage.scopes.firstParty.discovered}; ${manifest.coverage.counts.firstPartyScripts} scripts`,
    `- Addons: ${manifest.coverage.scopes.addons.scanned}/${manifest.coverage.scopes.addons.discovered}; ${manifest.coverage.counts.addonScripts} scripts`,
    `- Errors: ${manifest.coverage.errors.length}`,
  ];
  if (manifest.coverage.truncated) lines.push("- Boundary: files beyond the explicit scan cap are unknown, not absent.");
  lines.push(
    "",
    "## Graph summary",
    "",
    `- Entities: ${entities.length} (${[...kinds].map(([kind, values]) => `${kind} ${values.length}`).join(", ")})`,
    `- Relations: ${relations.length} (${[...relationCounts].sort(([a], [b]) => a.localeCompare(b)).map(([kind, count]) => `${kind} ${count}`).join(", ") || "none"})`,
    "",
  );
  appendEntities(lines, "Global classes", classesWithFacts(kinds.get("class") ?? [], "globalClass", true), 80);
  appendEntities(lines, "Scenes", kinds.get("scene") ?? [], 50);
  appendEntities(lines, "Resources", kinds.get("resource") ?? [], 50);
  appendEntities(lines, "Modules", kinds.get("module") ?? [], 80);
  appendEntities(lines, "Addons", kinds.get("addon") ?? [], 40);
  lines.push(
    "## Interpretation",
    "",
    "- Text-derived GDScript and Godot resource edges carry provenance and confidence; they are intentionally conservative.",
    "- `extends` represents script inheritance, `references` covers preloads and external resources, and `instantiates` identifies packed-scene instances.",
    "- Query with `queryBrain(projectPath, { query, kinds, limit })` for ranked entities and bounded graph neighbors.",
    "",
  );
  return lines.join("\n");
}

export const DEFAULT_CONVENTIONS_MD = `# Project Conventions

> Curated file. Knowledge refreshes preserve this file.

## Recorded conventions

_No project-specific conventions have been recorded yet._

## Godot Vibe OS workflow

- Use Godot tools for scene and resource mutations instead of editing serialized files directly.
- Verify GDScript parsing and resource import after changes.
- Keep autoload, input-map, and main-scene changes reflected in the project brain.
`;

function appendPaths(lines: string[], title: string, values: string[], limit: number): void {
  if (!values.length) return;
  lines.push(`## ${title}`, "");
  for (const value of values.slice(0, limit)) lines.push(`- \`${value}\``);
  if (values.length > limit) lines.push(`- …${values.length - limit} more`);
  lines.push("");
}

function appendEntities(lines: string[], title: string, entities: KnowledgeEntity[], limit: number): void {
  if (!entities.length) return;
  lines.push(`## ${title}`, "");
  for (const entity of entities.slice(0, limit)) lines.push(`- \`${entity.path ?? entity.name}\``);
  if (entities.length > limit) lines.push(`- …${entities.length - limit} more in \`entities.jsonl\``);
  lines.push("");
}

function groupByKind(entities: KnowledgeEntity[]): Map<string, KnowledgeEntity[]> {
  const output = new Map<string, KnowledgeEntity[]>();
  for (const entity of entities) {
    const values = output.get(entity.kind);
    if (values) values.push(entity);
    else output.set(entity.kind, [entity]);
  }
  return new Map([...output].sort(([a], [b]) => a.localeCompare(b)));
}

function classesWithFacts(
  entities: KnowledgeEntity[],
  key: string,
  value: KnowledgeEntity["facts"][number]["value"],
): KnowledgeEntity[] {
  return entities.filter((entity) => entity.facts.some((fact) => fact.key === key && fact.value === value));
}

function yesNo(value: boolean): string {
  return value ? "yes" : "no";
}
